# Ansible managed

default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: turnofarmBE

  username: vagrant
  password: turnodev

test:
  <<: *default
  database: turnofarmBE_test
